import type { Metadata } from "next";
import "@/Styles/global.css";
// import Footer from "@/components/Footer";
// i18n
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { getLangDir } from "rtl-detect";
import Config from "@/components/config/Config";
// import Navbar from "@/components/Navbar";
import Notification from "@/components/Notification";


export const metadata: Metadata = {
  title: "Tour Booking",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  const direction = getLangDir(locale);
  return (
    <html lang={locale} dir={direction}>
      <body className="relative">
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
        <Notification />
      </body>
      <Config />
    </html>
  );
}
