// isCode is 'ISO 3166-1-alpha-2' of a country
export const countries = [{
    name_en: "Iran",
    name_fa: "ایران",
    value:"iri",
    isoCode: "ir",
    cities: [{ name_en: "Mashhad", name_fa: "مشهد", value: "mashhad" },
    { name_en: "Tehran", name_fa: "تهران", value: "tehran" },
    { name_en: "Isfahan", name_fa: "اصفهان", value: "isfahan" },
    { name_en: "Shiraz", name_fa: "شیراز", value: "shiraz" },
    { name_en: "Tabriz", name_fa: "تبریز", value: "tabriz" },
    { name_en: "Kermanshah", name_fa: "کرمانشاه", value: "kermanshah" },
    { name_en: "Ahvaz", name_fa: "اهواز", value: "ahvaz" }]
}, {
    name_en: "United States",
    name_fa: "ایالات متحده آمریکا",
    value:"us",
    isoCode: "us",
    cities: [{ name_en: "Newyork City", name_fa: "نیویورک", value: "newyork" },
    { name_en: "Los Angeles", name_fa: "لس آنجلس", value: "la" },
    { name_en: "Chicago", name_fa: "شیکاگو", value: "chicago" },
    { name_en: "Houston", name_fa: "هوستون", value: "houston" },
    { name_en: "Phoenix", name_fa: "فونیکس", value: "phoenix" },
    { name_en: "Seattle", name_fa: "سیاتل", value: "seattle" },
    { name_en: "Austin", name_fa: "آستین", value: "austin" },
    { name_en: "Philadelphia", name_fa: "فیلادلفیا", value: "philadelphia" },
    { name_en: "Jacksonville", name_fa: "جکسونویل", value: "jacksonville" },]
}, {
    name_en: "Great Britain",
    name_fa: "انگلستان",
    value:"gb",
    isoCode: "gb",
    cities: [{ name_en: "London", name_fa: "لندن", value: "london" },
    { name_en: "Manchester", name_fa: "منچستر", value: "manchester" },
    { name_en: "Birmingham", name_fa: "بیرمنگام", value: "birmingham" },
    { name_en: "Leeds", name_fa: "لیدز", value: "leeds" },
    { name_en: "Glasgow", name_fa: "گلاسکو", value: "glasgow" },
    { name_en: "Sheffield", name_fa: "شفیلد", value: "sheffield" },
    { name_en: "Edinburgh", name_fa: "ادینبورو", value: "edinburgh" }]
}, {
    name_en: "China",
    name_fa: "چین",
    value:"prc",
    isoCode: "cn",
    cities: [{ name_en: "Beijing", name_fa: "پکن", value: "beijing" },
    { name_en: "Shanghai", name_fa: "شانگهای", value: "shanghai" },
    { name_en: "Shenzhen", name_fa: "شنژن", value: "shenzhen" },
    { name_en: "Guangzhou", name_fa: "گوانگ ژو", value: "guangzhou" },
    { name_en: "Chengdu", name_fa: "شانژو", value: "chengdu" },
    { name_en: "Tianjin", name_fa: "تیانجین", value: "tianjin" },
    { name_en: "Wuhan", name_fa: "ووهان", value: "wuhan" },
    { name_en: "Dongguan", name_fa: "دون گوان", value: "dongguan" },
    { name_en: "Chongqing", name_fa: "چونگ چینگ", value: "chongqing" },]
}, {
    name_en: "Germany",
    name_fa: "آلمان",
    value:"germany",
    isoCode: "de",
    cities: [{ name_en: "Berlin", name_fa: "برلین", value: "berlin" },
    { name_en: "Hamburg", name_fa: "هامبورگ", value: "hamburg" },
    { name_en: "Munich", name_fa: "مونیخ", value: "munich" },
    { name_en: "Cologne ", name_fa: "کلن", value: "cologne " },
    { name_en: "Frankfurt", name_fa: "فرانکفورت", value: "frankfurt" },
    ]
}, {
    name_en: "France",
    name_fa: "فرانسه",
    value:"france",
    isoCode: "fr",
    cities: [{ name_en: "Paris", name_fa: "پاریس", value: "paris" },
    { name_en: "Marseilles", name_fa: "مارسی", value: "marseilles" },
    { name_en: "Lyon", name_fa: "لیون", value: "lyon" },
    { name_en: "Toulouse ", name_fa: "تولوز", value: "toulouse " },
    { name_en: "Bordeaux", name_fa: "بوردو", value: "bordeaux" },
    ]
}, {
    name_en: "Spain",
    name_fa: "اسپانیا",
    value:"spain",
    isoCode: "es",
    cities: [{ name_en: "Madrid", name_fa: "مادرید", value: "madrid" },
    { name_en: "Barcelona", name_fa: "بارسلون", value: "barcelona" },
    { name_en: "Valencia", name_fa: "والنسیا", value: "Valencia" },
    { name_en: "Seville", name_fa: "سویل", value: "seville" },
    { name_en: "Bilbao", name_fa: "بیلبائو", value: "bilbao" },
    ]
}, {
    name_en: "Italy",
    name_fa: "ایتالیا",
    value:"italy",
    isoCode: "it",
    cities: [{ name_en: "Rome", name_fa: "رم", value: "rome" },
    { name_en: "Milan", name_fa: "میلان", value: "milan" },
    { name_en: "Naples", name_fa: "ناپل", value: "naples" },
    { name_en: "Turin ", name_fa: "تورین", value: "turin" },
    { name_en: "Palermo", name_fa: "پالرمو", value: "palermo" },
    { name_en: "Florence ", name_fa: "فلورانس", value: "florence" },
    { name_en: "Venice", name_fa: "ونیز", value: "venice" },
    ]
}, {
    name_en: "Ukraine",
    name_fa: "اوکراین",
    value:"ukraine",
    isoCode: "ua",
    cities: [{ name_en: "Kyiv", name_fa: "کیف", value: "kyiv" },
    { name_en: "Kharkiv", name_fa: "خارکیف", value: "kharkiv" },
    { name_en: "Odesa", name_fa: "ادسا", value: "odesa" },
    { name_en: "Dnipro", name_fa: "دنیپرو", value: "dnipro" },
    { name_en: "Lviv", name_fa: "لویو", value: "lviv" },
    ]
},]